package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"time"

	"genwaf/internal/controller"
	"genwaf/internal/policy"
)

func main() {
	controllerURL := flag.String("controller", "http://127.0.0.1:8080", "genctl base URL")
	outputPath := flag.String("output", "runtime/effective.json", "path to effective config output")
	decisionsPath := flag.String("decisions-output", "runtime/cluster-decisions.json", "path to shared decision output")
	observationsPath := flag.String("observations-input", "runtime/node-observations.json", "path to local node observations generated by gendp")
	rateLimitsPath := flag.String("rate-limits-output", "runtime/cluster-rate-limits.json", "path to shared multi-node rate pressure output")
	interval := flag.Duration("interval", 15*time.Second, "poll interval")
	once := flag.Bool("once", false, "fetch once and exit")
	nodeID := flag.String("node-id", "node-local", "node identifier for registration")
	nodeAddr := flag.String("node-addr", "127.0.0.1", "node address for registration")
	nodeRole := flag.String("node-role", "ingress", "node role for registration")
	nodeVersion := flag.String("node-version", "dev", "node version for registration")
	xdpLoaderPath := flag.String("xdp-loader", "./build/genxdp-loader", "path to genxdp-loader binary")
	xdpProfilePath := flag.String("xdp-profile-output", "runtime/xdp-profile.json", "path to compiled xdp profile output")
	xdpAutoApply := flag.Bool("xdp-auto-apply", true, "automatically compile/apply XDP when effective config changes")
	xdpStatsSeconds := flag.Int("xdp-stats-seconds", 0, "optional XDP stats watch window when auto-applying attach")
	flag.Parse()

	client := &http.Client{Timeout: 10 * time.Second}
	lastEffectiveSignature := ""
	if err := registerNode(client, *controllerURL, *nodeID, *nodeAddr, *nodeRole, *nodeVersion); err != nil {
		log.Fatalf("register node: %v", err)
	}
	log.Printf("registered node %s at %s with controller %s", *nodeID, *nodeAddr, *controllerURL)

	for {
		bundle, err := fetchBundle(client, *controllerURL)
		if err != nil {
			log.Fatalf("fetch cluster bundle: %v", err)
		}
		if err := writeEffectiveAtomically(*outputPath, bundle.Effective); err != nil {
			log.Fatalf("write effective config: %v", err)
		}
		if err := writeDecisionsAtomically(*decisionsPath, bundle); err != nil {
			log.Fatalf("write shared decisions: %v", err)
		}
		rateLimitOutputPath := *rateLimitsPath
		if bundle.Effective.SharedRateLimitPath != "" {
			rateLimitOutputPath = bundle.Effective.SharedRateLimitPath
		}
		if err := writeRateLimitsAtomically(rateLimitOutputPath, bundle); err != nil {
			log.Fatalf("write shared rate limits: %v", err)
		}
		signature, err := effectiveSignature(bundle.Effective)
		if err != nil {
			log.Fatalf("compute effective signature: %v", err)
		}
		if signature != lastEffectiveSignature {
			if err := syncXDP(*xdpLoaderPath, *outputPath, *xdpProfilePath, bundle.Effective, *xdpAutoApply, *xdpStatsSeconds); err != nil {
				log.Printf("xdp sync failed: %v", err)
			} else if bundle.Effective.XDPSyncFromController && *xdpAutoApply {
				log.Printf("applied XDP sync for mode=%s interface=%s attach_mode=%s", bundle.Effective.Mode, bundle.Effective.XDPInterface, bundle.Effective.XDPAttachMode)
			}
			lastEffectiveSignature = signature
		}
		postedCount := 0
		if batch, err := readObservationBatch(*observationsPath, *nodeID); err == nil && len(batch.Observations) > 0 {
			if err := postObservations(client, *controllerURL, batch); err != nil {
				log.Printf("post observations failed: %v", err)
			} else {
				postedCount = len(batch.Observations)
			}
		}
		log.Printf("synced effective mode=%s version=%d to %s, %d shared decisions to %s, and %d shared observations to %s",
			bundle.Effective.Mode, bundle.CurrentVersion.Version, *outputPath, len(bundle.SharedDecisions), *decisionsPath, len(bundle.SharedObservations), rateLimitOutputPath)

		if err := heartbeatNode(client, *controllerURL, controller.NodeHeartbeat{
			NodeID:            *nodeID,
			Address:           *nodeAddr,
			Role:              *nodeRole,
			Version:           *nodeVersion,
			LastAckVersion:    bundle.CurrentVersion.Version,
			LastAckMode:       bundle.Effective.Mode,
			DecisionSyncCount: len(bundle.SharedDecisions) + postedCount,
		}); err != nil {
			log.Fatalf("heartbeat node: %v", err)
		}

		if *once {
			return
		}
		time.Sleep(*interval)
	}
}

func fetchBundle(client *http.Client, baseURL string) (controller.ClusterBundle, error) {
	resp, err := client.Get(baseURL + "/v1/cluster/bundle")
	if err != nil {
		return controller.ClusterBundle{}, fmt.Errorf("GET cluster bundle: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return controller.ClusterBundle{}, fmt.Errorf("controller returned status %s", resp.Status)
	}

	var bundle controller.ClusterBundle
	if err := json.NewDecoder(resp.Body).Decode(&bundle); err != nil {
		return controller.ClusterBundle{}, fmt.Errorf("decode cluster bundle: %w", err)
	}
	return bundle, nil
}

func registerNode(client *http.Client, baseURL, nodeID, address, role, version string) error {
	payload := map[string]any{
		"node_id":      nodeID,
		"address":      address,
		"role":         role,
		"version":      version,
		"capabilities": []string{"effective-config-sync", "shared-decision-sync", "shared-rate-limit-sync", "xdp-runtime-sync", "rollout-ack"},
	}
	raw, err := json.Marshal(payload)
	if err != nil {
		return fmt.Errorf("marshal node registration: %w", err)
	}

	resp, err := client.Post(baseURL+"/v1/nodes/register", "application/json", bytes.NewReader(raw))
	if err != nil {
		return fmt.Errorf("POST node registration: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("controller returned status %s on registration", resp.Status)
	}
	return nil
}

func heartbeatNode(client *http.Client, baseURL string, heartbeat controller.NodeHeartbeat) error {
	raw, err := json.Marshal(heartbeat)
	if err != nil {
		return fmt.Errorf("marshal heartbeat: %w", err)
	}
	resp, err := client.Post(baseURL+"/v1/nodes/heartbeat", "application/json", bytes.NewReader(raw))
	if err != nil {
		return fmt.Errorf("POST heartbeat: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("controller returned status %s on heartbeat", resp.Status)
	}
	return nil
}

func writeEffectiveAtomically(path string, effective policy.EffectiveConfig) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("mkdir output dir: %w", err)
	}

	raw, err := json.MarshalIndent(effective, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal effective config: %w", err)
	}

	tmpPath := path + ".tmp"
	if err := os.WriteFile(tmpPath, raw, 0o644); err != nil {
		return fmt.Errorf("write temp file: %w", err)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		return fmt.Errorf("rename temp file: %w", err)
	}
	return nil
}

func writeDecisionsAtomically(path string, bundle controller.ClusterBundle) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("mkdir decisions dir: %w", err)
	}
	payload := struct {
		GeneratedAt time.Time           `json:"generated_at"`
		Version     int                 `json:"version"`
		Mode        string              `json:"mode"`
		Decisions   []decisionFileEntry `json:"decisions"`
	}{
		GeneratedAt: bundle.GeneratedAt,
		Version:     bundle.CurrentVersion.Version,
		Mode:        bundle.Effective.Mode,
		Decisions:   make([]decisionFileEntry, 0, len(bundle.SharedDecisions)),
	}
	for _, decision := range bundle.SharedDecisions {
		payload.Decisions = append(payload.Decisions, decisionFileEntry{
			ID:            decision.ID,
			ClientIP:      decision.ClientIP,
			FingerprintID: decision.FingerprintID,
			Action:        decision.Action,
			Reason:        decision.Reason,
			Source:        decision.Source,
			CreatedAt:     decision.CreatedAt,
			ExpiresAt:     decision.ExpiresAt,
			ExpiresAtUnix: decision.ExpiresAt.Unix(),
		})
	}
	raw, err := json.MarshalIndent(payload, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal shared decisions: %w", err)
	}
	tmpPath := path + ".tmp"
	if err := os.WriteFile(tmpPath, raw, 0o644); err != nil {
		return fmt.Errorf("write temp decision file: %w", err)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		return fmt.Errorf("rename temp decision file: %w", err)
	}
	return nil
}

func writeRateLimitsAtomically(path string, bundle controller.ClusterBundle) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("mkdir rate-limit dir: %w", err)
	}
	type rateLimitEntry struct {
		ClientIP          string `json:"client_ip"`
		Requests          int    `json:"requests"`
		ChallengeFailures int    `json:"challenge_failures"`
		SensitiveHits     int    `json:"sensitive_hits"`
		ReputationScore   int    `json:"reputation_score"`
		LastNodeID        string `json:"last_node_id"`
		WindowSeconds     int    `json:"window_seconds"`
		ExpiresAtUnix     int64  `json:"expires_at"`
	}
	entries := make([]rateLimitEntry, 0, len(bundle.SharedObservations))
	now := time.Now().UTC()
	for _, item := range bundle.SharedObservations {
		windowSeconds := int(item.ExpiresAt.Sub(now).Seconds())
		if windowSeconds < 1 {
			windowSeconds = 1
		}
		entries = append(entries, rateLimitEntry{
			ClientIP:          item.ClientIP,
			Requests:          item.Requests,
			ChallengeFailures: item.ChallengeFailures,
			SensitiveHits:     item.SensitiveHits,
			ReputationScore:   item.ReputationScore,
			LastNodeID:        item.LastNodeID,
			WindowSeconds:     windowSeconds,
			ExpiresAtUnix:     item.ExpiresAt.Unix(),
		})
	}
	payload := struct {
		GeneratedAt  time.Time        `json:"generated_at"`
		Version      int              `json:"version"`
		Mode         string           `json:"mode"`
		Observations []rateLimitEntry `json:"observations"`
	}{
		GeneratedAt:  bundle.GeneratedAt,
		Version:      bundle.CurrentVersion.Version,
		Mode:         bundle.Effective.Mode,
		Observations: entries,
	}
	raw, err := json.MarshalIndent(payload, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal shared rate limits: %w", err)
	}
	tmpPath := path + ".tmp"
	if err := os.WriteFile(tmpPath, raw, 0o644); err != nil {
		return fmt.Errorf("write temp rate-limit file: %w", err)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		return fmt.Errorf("rename temp rate-limit file: %w", err)
	}
	return nil
}

type decisionFileEntry struct {
	ID            string    `json:"id"`
	ClientIP      string    `json:"client_ip"`
	FingerprintID string    `json:"fingerprint_id,omitempty"`
	Action        string    `json:"action"`
	Reason        string    `json:"reason"`
	Source        string    `json:"source"`
	CreatedAt     time.Time `json:"created_at"`
	ExpiresAt     time.Time `json:"expires_at"`
	ExpiresAtUnix int64     `json:"expires_at_unix"`
}

type observationFile struct {
	GeneratedAt   time.Time                      `json:"generated_at"`
	WindowSeconds int                            `json:"window_seconds"`
	Observations  []controller.ClientObservation `json:"observations"`
}

func readObservationBatch(path, nodeID string) (controller.ObservationBatch, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return controller.ObservationBatch{}, nil
		}
		return controller.ObservationBatch{}, fmt.Errorf("read observations: %w", err)
	}

	var payload observationFile
	if err := json.Unmarshal(raw, &payload); err != nil {
		return controller.ObservationBatch{}, fmt.Errorf("decode observations: %w", err)
	}
	for i := range payload.Observations {
		payload.Observations[i].NodeID = nodeID
	}
	return controller.ObservationBatch{
		NodeID:        nodeID,
		GeneratedAt:   payload.GeneratedAt,
		WindowSeconds: payload.WindowSeconds,
		Observations:  payload.Observations,
	}, nil
}

func postObservations(client *http.Client, baseURL string, batch controller.ObservationBatch) error {
	raw, err := json.Marshal(batch)
	if err != nil {
		return fmt.Errorf("marshal observations: %w", err)
	}
	resp, err := client.Post(baseURL+"/v1/cluster/observations", "application/json", bytes.NewReader(raw))
	if err != nil {
		return fmt.Errorf("POST observations: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("controller returned status %s on observations", resp.Status)
	}
	return nil
}

func effectiveSignature(effective policy.EffectiveConfig) (string, error) {
	raw, err := json.Marshal(effective)
	if err != nil {
		return "", err
	}
	return string(raw), nil
}

func syncXDP(loaderPath, effectivePath, profilePath string, effective policy.EffectiveConfig, autoApply bool, statsSeconds int) error {
	if loaderPath == "" {
		return nil
	}
	baseArgs := []string{"--config", effectivePath, "--output", profilePath}
	if !autoApply || !effective.XDPSyncFromController {
		cmd := exec.Command(loaderPath, baseArgs...)
		if output, err := cmd.CombinedOutput(); err != nil {
			return fmt.Errorf("compile xdp profile: %w: %s", err, string(output))
		}
		return nil
	}

	args := append([]string{}, baseArgs...)
	if effective.XDPEnabled {
		args = append(args, "--attach")
		if effective.XDPInterface != "" {
			args = append(args, "--iface", effective.XDPInterface)
		}
		if effective.XDPAttachMode != "" {
			args = append(args, "--attach-mode", effective.XDPAttachMode)
		}
		if statsSeconds > 0 {
			args = append(args, "--stats-seconds", fmt.Sprintf("%d", statsSeconds))
		}
	} else {
		args = append(args, "--detach")
		if effective.XDPInterface != "" {
			args = append(args, "--iface", effective.XDPInterface)
		}
		if effective.XDPAttachMode != "" {
			args = append(args, "--attach-mode", effective.XDPAttachMode)
		}
	}
	cmd := exec.Command(loaderPath, args...)
	if output, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("apply xdp sync: %w: %s", err, string(output))
	}
	return nil
}
